import axios from 'axios';
import Head from 'next/head';
import Cookies from 'js-cookie';
import { useState } from 'react';
import NextLink from 'next/link';
import { useEffect } from 'react';
import { Store } from '../utils/Store';
import useStyles from '../utils/styles';
import { useRouter } from 'next/router';
import { useSnackbar } from 'notistack';
import React, { useContext } from 'react';
import { getError } from '../utils/error';
import MenuIcon from '@material-ui/icons/Menu';
import CancelIcon from '@material-ui/icons/Cancel';
import SearchIcon from '@material-ui/icons/Search';
import { AppBar, Toolbar, Typography, Container, Link, createMuiTheme, ThemeProvider, CssBaseline, Switch, Badge, Button, Menu, MenuItem, Box, IconButton, Drawer, List, ListItem, Divider, ListItemText, InputBase, from } from '@material-ui/core';

function Layout({ children }) {
	return (
		<div>
			<Head>
                <title>Ubwonko</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <AppBar position='static'>
            	<Toolbar>
            		<Typography>UBWONKO</Typography>
            	</Toolbar>
            </AppBar>
            <Container>
            	{ children }
            </Container>
            <footer>
            	<Typography>
            		All right reserved. Ubwonko 2022
            	</Typography>
            </footer>
		</div>
	)
}

export default Layout